### ISSUE TITLE
Make the Website Responsive

### ISSUE THREAD

**Issue by ksdkamesh99** [ksdkamesh99/KNN-Visualiser#3]
Need to make the website responsive using bootstrap

**Comment by koskrit** [comment]
Hi Kamesh, I'd like to help you with this issue.

**Comment by ksdkamesh99** [comment]
Sure @koskrit

**Comment by koskrit** [comment]
Good day Kamesh. I edited the grid of the canvas

![Grid Example](https://i.imgur.com/bhisU8K.png)

Though those floating canvas buttons, are getting in the way of the visualizer. So...

On another branch I pushed them in a div with some DOM-manipulation.

![buttons-on-div](https://i.imgur.com/qq219By.png)

------

Would you prefer the buttons to be positioned with the knn.js in the first pic. Or dynamically 

using Dom manipulation similar to the second pic? 

P.S If you have another suggestion in mind please let me know.

**Comment by ksdkamesh99** [comment]
Second One Looks nice
